version: 2

updates:
  # Update npm packages
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 10

    # Group packages into shared PR
    groups:
      build:
        patterns:
          - '@babel/*'
          - '@defra/hapi-connect'
          - '@vitest/coverage-v8'
          - 'cheerio'
          - 'cross-env'
          - 'eslint'
          - 'vite'
          - 'sass-embedded'
          - 'sass-*'

      lint:
        patterns:
          - 'neostandard'
          - 'prettier'
          - 'stylelint'
          - 'stylelint-*'
          - 'stylelint-config-gds'

      logging:
        patterns:
          - '*-pino'
          - '*-pino-format'
          - 'pino'
          - 'pino-*'
          - 'pino-pretty'

      runtime:
        patterns:
          - '@aws-sdk/*'
          - '@azure/*'
          - '@defra/*'
          - '@elastic/*'
          - '@hapi/*'
          - 'blankie'
          - 'convict'
          - 'convict-format-with-validator'
          - 'cssnano'
          - 'cssnano-preset-default'
          - 'date-fns'
          - 'govuk-frontend'
          - 'hapi-pino'
          - 'hapi-pulse'
          - 'ioredis'
          - 'lodash'
          - 'nunjucks'
          - 'pino'

      tools:
        patterns:
          - 'husky'
          - 'vitest'
          - 'vitest-*'
          - 'vitest-fetch-mock'
          - 'nodemon'
          - 'npm-run-all'
          - 'postcss-*'

      types:
        patterns:
          - '@types/*'

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'

    versioning-strategy: increase

    allow:
      # Include direct package.json updates
      - dependency-type: direct

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: /

    # Schedule run every Monday, local time
    schedule:
      interval: weekly
      time: '10:30'
      timezone: 'Europe/London'
